version: "3.9"

services:
  database-postgres:
    hostname: database-postgres
    container_name: database-postgres
    image: postgres:15.3-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - persistence

  cache-redis:
    hostname: cache-redis
    restart: always
    container_name: cache-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - persistence

  job-queue-redis:
    hostname: job-queue-redis
    container_name: job-queue-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6380
    image: bitnami/redis:latest
    ports:
      - "6380:6380"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - persistence

volumes:
  database:
  cache:

networks:
  persistence:
    name: persistence
    driver: bridge
