version: "3.9"

services:
  database-postgres:
    hostname: database-postgres
    container_name: database-postgres
    image: postgres:15.3-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - persistence

  cache-redis:
    hostname: cache-redis
    restart: always
    container_name: cache-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=6379
    image: bitnami/redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - cache:/bitnami/redis/data
    networks:
      - persistence

  job-queue-redis:
    hostname: job-queue-redis
    container_name: job-queue-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=6380
    image: bitnami/redis:7.0
    ports:
      - "6380:6380"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - job-queue:/bitnami/redis/data
    networks:
      - persistence

  duplicate-table-redis:
    hostname: duplicate-table-redis
    container_name: duplicate-table-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=6381
    image: bitnami/redis:7.0
    ports:
      - "6381:6381"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - duplicate-table:/bitnami/redis/data
    networks:
      - persistence

  keyword-dragonflydb-write-0:
    hostname: keyword-dragonflydb-write-0
    container_name: keyword-dragonflydb-write-0
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.10.0
    entrypoint:
      - dragonfly
    command:
      - --port=6382
      - --cluster_mode=emulated
      - --requirepass=${REDIS_PASSWORD}
      - --masterauth=${REDIS_PASSWORD}
    ulimits:
      memlock: -1
    ports:
      - "6382:6382"
    networks:
      - persistence
    volumes:
      - keyword-dragonflydb-write-0:/data

  keyword-dragonflydb-read-0:
    hostname: keyword-dragonflydb-read-0
    container_name: keyword-dragonflydb-read-0
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.10.0
    ports:
      - "6383:6379"
    entrypoint:
      - dragonfly
    command:
      - --cluster_mode=emulated
      - --requirepass=${REDIS_PASSWORD}
      - --masterauth=${REDIS_PASSWORD}
      - --replicaof
      - keyword-dragonflydb-write-0:6382
    ulimits:
      memlock: -1
    depends_on:
      - keyword-dragonflydb-write-0
    networks:
      - persistence
    volumes:
      - keyword-dragonflydb-read-0:/data

volumes:
  database:
  cache:
  job-queue:
  duplicate-table:
  keyword-dragonflydb-write-0:
    name: keyword-dragonflydb-write-0
  keyword-dragonflydb-read-0:
    name: keyword-dragonflydb-read-0

networks:
  persistence:
    name: persistence
    driver: bridge
