http:
  routers:
    router-broker-dashboard:
      rule: "Host(`broker.${DOMAIN_NAME}`)"
      service: broker-dashboard

    router-monitor:
      rule: "Host(`monitor.${DOMAIN_NAME}`)"
      service: monitor

    router-traefik:
      rule: "Host(`traefik.${DOMAIN_NAME}`)"
      service: api@internal


  services:
    broker-dashboard:
      loadBalancer:
        servers:
          - url: "http://memphis:9000"

    monitor:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"